import Head from "next/head";
import { useRef, useState } from "react";
import SearchModal from "../components/SearchModal";
import useCommandKCombo from "../hooks/useCmdPlusK";

export default function Home() {
  const [showModal, toggleModal] = useState(false);
  const btnRef = useRef<any>();
  useCommandKCombo(toggleModal, btnRef);
  return (
    <div>
      <Head>
        <title>Sovtech </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="max-w-4xl mx-auto my-10">
        <button
          className="flex border-[1px] py-2 px-3 rounded-lg w-72 justify-between items-center text-slate-400  hover:border-slate-300 transition-all text-sm "
          onClick={() => {
            toggleModal(!showModal);
          }}
          ref={btnRef}
        >
          <div className="flex items-center">
            <svg
              width="24"
              height="24"
              fill="none"
              aria-hidden="true"
              className="mr-3 flex-none"
            >
              <path
                d="m19 19-3.5-3.5"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
              ></path>
              <circle
                cx="11"
                cy="11"
                r="6"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
              ></circle>
            </svg>

            <span>Search films...</span>
          </div>
          <div>⌘K</div>
        </button>

        {showModal && (
          <SearchModal toggleModal={toggleModal} isOpen={showModal} />
        )}
      </main>

      <footer></footer>
    </div>
  );
}
