import { GetStaticProps } from "next";
import Head from "next/head";
import { useContext } from "react";
import SearchModal from "../components/SearchModal";
import { FILMS_URL, getPosterURL } from "../utils/constants";
import { fetcher } from "../utils/fetcher";
import { Nav } from "../components/Nav";

import AppContext from "../components/AppContext";
import SearchButton from "../components/SearchButton";
import MoviesGrid from "../components/MoviesGrid";
import { Film } from "../components/MovieCard";

export default function Home(props: { films: Film[] }) {
  const { showModal } = useContext(AppContext);

  const { films } = props;

  return (
    <div className="">
      <Head>
        <title>Sovtech </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <header>
        <Nav />
      </header>
      <main className="mx-auto container mt-24">
        <SearchButton />
        {showModal && <SearchModal />}
        <MoviesGrid films={films} />
      </main>
    </div>
  );
}

export const getStaticProps: GetStaticProps = async (context) => {
  const filmsData = await fetcher(FILMS_URL);

  const films = filmsData.results.slice(0, 6).map((film: Film) => {
    return {
      ...film,
      posterUrl: getPosterURL(film.url, "films"),
    };
  });

  return {
    props: { films },
  };
};
