import { GetServerSideProps, GetStaticProps } from "next";
import Head from "next/head";
import { useRef, useState } from "react";
import useSWR from "swr";
import MovieCard from "../components/MovieCard";
import SearchModal from "../components/SearchModal";
import useCommandKCombo from "../hooks/useCmdPlusK";
import { API_BASE_URL, FILMS_URL, getPosterURL } from "../utils/constants";
import { fetcher } from "../utils/fetcher";

import Image from "next/image";
export default function Home(props: any) {
  const [showModal, toggleModal] = useState(false);
  const btnRef = useRef<any>();

  {
    /*
    The useCommandKCombo hook is used to detect when the user presses the command key and K together.
    */
  }
  useCommandKCombo(toggleModal, btnRef);
  return (
    <div className="bg-red-50 h-100vh">
      <Head>
        <title>Sovtech </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav>
          <div className="container mx-auto flex items-center justify-between px-4 py-2">
            <Image src="/logo.png" alt="logo" height={30} width={30} />
          </div>
        </nav>
      </header>
      <main className="mx-auto container">
        <button
          className="flex border-[1px] py-4 px-3 rounded-lg  w-full justify-between items-center text-slate-400  hover:border-slate-300 transition-all text-sm bg-white mx-6 "
          onClick={() => {
            toggleModal(!showModal);
          }}
          ref={btnRef}
        >
          <div className="flex items-center">
            <svg
              width="24"
              height="24"
              fill="none"
              aria-hidden="true"
              className="mr-3 flex-none"
            >
              <path
                d="m19 19-3.5-3.5"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
              ></path>
              <circle
                cx="11"
                cy="11"
                r="6"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
              ></circle>
            </svg>

            <span>Search films...</span>
          </div>
          <div>⌘K</div>
        </button>

        {showModal && (
          <SearchModal toggleModal={toggleModal} isOpen={showModal} />
        )}
        <div className="bg-white rounded-lg p-12 mx-6 mt-6">
          <h5 className="p-4">Latest Films</h5>
          <div className="grid grid-cols-3 gap-6 ">
            {props.films.map((film: any) => (
              <MovieCard film={film} />
            ))}
          </div>
        </div>
      </main>

      <footer></footer>
    </div>
  );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const data = await fetcher(FILMS_URL);

  const films = (data.results = data.results.map((film: any) => {
    return {
      ...film,
      posterUrl: getPosterURL(film.episode_id),
    };
  }));

  return {
    props: { films },
  };
};
